- name: Configure workstation
  hosts: workstations
  roles:
    - misc_packages
    - gnome
    - shell
    - git
    - nautilus
    - role: gantsign.visual-studio-code
      users:
        - username: "{{ ansible_user_id }}"
          visual_studio_code_settings: {
            "window.titleBarStyle": "custom"
          }
- name: Configure for playings games
  hosts: gaming
  roles:
    - steam
    - goggalaxy
- name: Configure for CAD and 3D printing
  hosts: cad
  roles:
    - prusaslicer
