- name: Check/generates a gpg key
  block:
  - name: Check if gpg key exists
    ansible.builtin.shell: gpg --list-secret-keys --keyid-format LONG {{ git.email }} | grep --only-matching --extended-regexp '[A-Z0-9]{40}'
    register: gpg_key_id
    failed_when: gpg_key_id.rc > 1
    changed_when: false
  - name: Generate a key if it is required
    ansible.builtin.shell: |
      gpg --batch --passphrase '' --quick-gen-key "{{ git.name }} <{{ git.email }}>"
      gpg --list-secret-keys --keyid-format LONG {{ git.email }} | grep --only-matching --extended-regexp '[A-Z0-9]{40}'
    register: gpg_key_id
    changed_when: gpg_key_id.rc != 0

- name: Applies .gitconfig
  ansible.builtin.template:
    src: .gitconfig.j2
    dest: "/home/{{ ansible_user_id }}/.gitconfig"
    mode: 0644
